# Generated by Django 5.0.10 on 2025-01-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSalud',
            fields=[
                ('id_estado_salud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_salud', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'estado_salud',
                'verbose_name_plural': 'estados_salud',
                'db_table': 'estado_salud',
                'ordering': ['id_estado_salud'],
            },
        ),
    ]
