# Generated by Django 5.0.10 on 2025-01-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosalud',
            name='descripcion',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
