# Generated by Django 5.0.10 on 2025-01-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estado_salud', '0002_estadosalud_descripcion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadosalud',
            table='estados_salud',
        ),
    ]
