# Generated by Django 5.0.10 on 2025-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id_tipo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_proveedor', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'tipo_proveedor',
                'verbose_name_plural': 'tipos_proveedor',
                'db_table': 'tipos_proveedor',
                'ordering': ['id_tipo_proveedor'],
            },
        ),
    ]
