# Generated by Django 5.0.10 on 2025-01-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=56, unique=True)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'paises',
                'ordering': ['id_pais'],
            },
        ),
    ]
