# Generated by Django 5.0.10 on 2025-01-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitats',
            fields=[
                ('id_habitat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_habitat', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='images/habitats')),
            ],
            options={
                'verbose_name': 'Habitat',
                'verbose_name_plural': 'Habitats',
                'db_table': 'Habitats',
                'ordering': ['id_habitat'],
            },
        ),
    ]
