# Generated by Django 5.0.10 on 2025-01-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0003_alter_habitats_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitats',
            name='descripcion',
            field=models.CharField(default=None, max_length=2555),
        ),
    ]
