# Generated by Django 5.0.10 on 2025-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSuministro',
            fields=[
                ('id_tipo_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_suministro', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'tipo_suministro',
                'verbose_name_plural': 'tipos_suministros',
                'db_table': 'tipos_suministros',
                'ordering': ['id_tipo_suministro'],
            },
        ),
    ]
