# Generated by Django 5.0.10 on 2025-01-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_empleado', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'tipo_empleado',
                'verbose_name_plural': 'tipos_empleados',
                'db_table': 'tipos_empleados',
                'ordering': ['id_tipo_empleado'],
            },
        ),
    ]
