# Generated by Django 5.0.10 on 2025-01-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlimentacion',
            fields=[
                ('id_tipo_alimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_alimentacion', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'tipo_alimentacion',
                'verbose_name_plural': 'tipos_alimentacion',
                'db_table': 'tipo_alimentacion',
                'ordering': ['id_tipo_alimentacion'],
            },
        ),
    ]
