# Generated by Django 5.0.10 on 2025-01-04 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_alimentacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especie', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='images/especies')),
                ('id_tipo_alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_alimentacion.tipoalimentacion')),
            ],
            options={
                'verbose_name': 'especie',
                'verbose_name_plural': 'especies',
                'db_table': 'especies',
                'ordering': ['id_especie'],
            },
        ),
    ]
