# Generated by Django 5.0.10 on 2025-01-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especies',
            name='descripcion',
            field=models.CharField(default='Descripción no disponible', max_length=2555),
        ),
    ]
