# Generated by Django 5.0.10 on 2025-01-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0002_especies_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especies',
            name='descripcion',
            field=models.CharField(default='', max_length=2555),
        ),
    ]
