# Generated by Django 5.0.10 on 2025-01-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriasAnimales',
            fields=[
                ('id_subcategoria_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'subcategoria_animal',
                'verbose_name_plural': 'subcategorias_animales',
                'db_table': 'subcategorias_animales',
                'ordering': ['id_subcategoria_animal'],
            },
        ),
    ]
