# Generated by Django 5.0.10 on 2025-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategoria_animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoriasanimales',
            name='descripción',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
