# Generated by Django 5.0.10 on 2025-01-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategoria_animal', '0002_subcategoriasanimales_descripción'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoriasanimales',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
