# Generated by Django 5.0.10 on 2025-01-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategoria_animal', '0003_rename_descripción_subcategoriasanimales_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriasanimales',
            name='descripcion',
            field=models.CharField(default=None, max_length=2555),
        ),
    ]
