# Generated by Django 5.0.10 on 2025-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id_tipo_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_animal', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'verbose_name': 'tipo_animal',
                'verbose_name_plural': 'tipos_animales',
                'db_table': 'tipo_animal',
                'ordering': ['id_tipo_animal'],
            },
        ),
    ]
