# Generated by Django 5.0.10 on 2025-01-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continentes',
            fields=[
                ('id_continente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_continente', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'continente',
                'verbose_name_plural': 'continentes',
                'db_table': 'continentes',
                'ordering': ['id_continente'],
            },
        ),
    ]
