# Generated by Django 5.0.10 on 2025-01-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposZonas',
            fields=[
                ('id_tipo_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_zona', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(default=None, max_length=255)),
            ],
            options={
                'verbose_name': 'tipo_zona',
                'verbose_name_plural': 'tipos_zonas',
                'db_table': 'tipos_zonas',
                'ordering': ['id_tipo_zona'],
            },
        ),
    ]
